#!/bin/bash

cd "$(dirname "$0")"
cwd=`pwd`

./MakeClean 2>> log
exec &> outlog

echo "[`date`] Starting DoAll script" | tee -a log

mkdir -p auto/tmp auto/html

# Create virtual environment
cd ${cwd}
echo "[`date`] Creating virtual environment" | tee -a log
./MakeVirtualEnvironment 2>> log

# Activate virtual environment
cd ${cwd}
echo "[`date`] Activating virtual environment" | tee -a log
source auto/virtualenv/bin/activate

# Initialise databases
cd ${cwd}
echo "[`date`] Initialising databases" | tee -a log
cd build/initdb
python main_initdb.py 2>> ../../log

# Generate SQL dump
cd ${cwd}
echo "[`date`] Making sql dump" | tee -a log
cd auto
mysqldump --defaults-extra-file=mysql_login.cfg adsb | gzip > mysqlDump.sql.gz 2>> ../log

cd ${cwd}
echo "[`date`] Finishing DoAll script" | tee -a log
